name: 'Tenable Cloud Security IaC Sync Terraform'
description: 'Sync IaC'
branding:
  color: 'blue'
  icon: 'shield'

inputs:
  api-token:
    description: ''
    required: true
  api-url:
    description: ''
    required: true
  code-branch:
    default: ${{ github.event_name != 'pull_request' && github.ref_name || github.head_ref }}
    description: ''
    required: false
  code-commit-hash:
    default: ${{ github.sha }}
    description: ''
    required: false
  code-commit-user:
    default: ${{ github.actor }}
    description: ''
    required: false
  code-repository-url:
    default: ${{ github.server_url }}/${{ github.repository }}
    description: ''
    required: false
  logs:
    default: 'false'
    description: ''
    required: false
  path:
    description: ''
    required: false
  pipeline-run-id:
    default: ${{ github.run_id }}
    description: ''
    required: false
  pipeline-run-trigger:
    default: ${{ github.event_name }}
    description: ''
    required: false
  pipeline-run-url:
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    description: ''
    required: false
  silent:
    default: 'false'
    description: ''
    required: false
  state-file-path:
    default: 'terraform.tfstate'
    description: ''
    required: false

runs:
  using: 'docker'
  image: 'docker://tenable/cloud-security-scanner:latest'
  args:
    - iac
    - sync
    - terraform
    - ${{ inputs.logs != 'false' &&  '--logs' || ''}}
    - ${{ inputs.path &&  '--path'}}
    - ${{ inputs.path }}
    - ${{ inputs.silent != 'false' &&  '--silent' || ''}}
  env:
    TENABLE_API_TOKEN: ${{ inputs.api-token }}
    TENABLE_API_URL: ${{ inputs.api-url }}
    TENABLE_CODE_BRANCH: ${{ inputs.code-branch }}
    TENABLE_CODE_COMMIT_HASH: ${{ inputs.code-commit-hash }}
    TENABLE_CODE_COMMIT_USER: ${{ inputs.code-commit-user }}
    TENABLE_CODE_REPOSITORY_URL: ${{ inputs.code-repository-url }}
    TENABLE_PIPELINE_RUN_ID: ${{ inputs.pipeline-run-id }}
    TENABLE_PIPELINE_RUN_TRIGGER: ${{ inputs.pipeline-run-trigger }}
    TENABLE_PIPELINE_RUN_URL: ${{ inputs.pipeline-run-url }}
    TENABLE_STATE_FILE_PATH: ${{ inputs.state-file-path }}
